name: icecast_flutter
description: "A Flutter plugin for streaming audio to icecast."
version: 0.0.2
homepage: https://github.com/MrKhay/icecast_flutter/blob/master/example/lib/main.dart

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.ikhaydev.icecast.icecast_flutter
        pluginClass: IcecastFlutterPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
